name: Auto-deploy React App

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - ".github/workflows/autodeploy.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.x
          cache: "npm"
          cache-dependency-path: ./app/package-lock.json

      - name: Install pkgs and build.
        run: |
          cd ./app/;
          npm ci;
          npm run build --if-present;

      - name: Deploy app to GH pages.
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git config remote.origin.url 'https://${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git'
          cd ./app/;

          npm run deploy
        env:
          user_name: "ArielMAJ"
          user_email: "ariel.maj@hotmail.com"
